module.exports = {
    CED_HEAD: 'CED_HEAD',
    LABORATORY_HEAD: 'LABORATORY_HEAD',
    RESEARCHER: 'RESEARCHER',
    ADMIN: 'ADMIN',
    TEAM_HEAD: 'TEAM_HEAD',
    RESEARCH_DIRECTOR: 'RESEARCH_DIRECTOR',
    VICE_CED_HEAD:'VICE_CED_HEAD'
}
